spring.application.name=Concesionario
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.nfvoosigshcdsgssagxw
spring.datasource.password=Alozaina.12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
